import Link from "next/link";
import { ArrowRight, Check, ChevronDown, Play, Sparkles } from "lucide-react";

const features = [{ title: "One workspace", text: "Keep every idea, asset, and caption moving in one calm, focused place." }, { title: "Built for flow", text: "Compose once, shape your story for each channel, then let your calendar do the rest." }, { title: "Clarity at a glance", text: "See what is coming up, what is live, and what needs your attention without digging." }];
const steps = [["01", "Bring your idea", "Drop in a photo or video, write the thought, and add the little details that make it yours."], ["02", "Shape the moment", "Choose where it belongs. OnePost keeps your media and message together as you refine the post."], ["03", "Send it out", "Publish when you are ready or schedule a quieter moment. Your queue stays easy to understand."]];

export default function Home() {
  return <main className="min-h-screen overflow-hidden bg-[#f7f8f3] text-[#14211f]">
    <nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-10"><Link href="/" className="flex items-center gap-2 text-lg font-semibold tracking-tight"><span className="flex h-8 w-8 items-center justify-center rounded-[10px] bg-[#14211f] text-[#d7f36a]"><Sparkles size={16} /></span>OnePost</Link><div className="hidden items-center gap-9 text-sm text-[#63706b] md:flex"><a href="#features">Features</a><a href="#how-it-works">How it works</a><a href="#pricing">Pricing</a></div><div className="flex items-center gap-3"><Link href="/auth/login" className="hidden px-3 py-2 text-sm font-medium text-[#63706b] sm:block">Log in</Link><Link href="/auth/signup" className="rounded-full bg-[#14211f] px-4 py-2.5 text-sm font-medium text-white">Get started <ArrowRight className="ml-1 inline" size={15} /></Link></div></nav>
    <section className="mx-auto grid max-w-7xl items-center gap-14 px-6 pb-24 pt-16 lg:grid-cols-[1.05fr_.95fr] lg:px-10 lg:pb-32 lg:pt-24"><div><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-[#dfe5d7] bg-white/70 px-3 py-1.5 text-xs font-medium text-[#63706b]"><span className="h-1.5 w-1.5 rounded-full bg-[#96bd30]" /> The calmer way to show up online</div><h1 className="max-w-2xl text-5xl font-semibold leading-[1.04] tracking-[-0.055em] sm:text-6xl lg:text-7xl">Create once.<br /><span className="text-[#7f9f2e]">Publish everywhere.</span></h1><p className="mt-7 max-w-lg text-lg leading-8 text-[#63706b]">OnePost brings your content, calendar, and social channels into one focused workspace, so more of your energy goes into the work itself.</p><div className="mt-9 flex flex-wrap items-center gap-4"><Link href="/auth/signup" className="rounded-full bg-[#14211f] px-6 py-3.5 text-sm font-medium text-white">Start creating free <ArrowRight className="ml-2 inline" size={16} /></Link><button className="flex items-center gap-2 px-2 py-3 text-sm font-medium text-[#63706b]"><span className="flex h-8 w-8 items-center justify-center rounded-full border border-[#ccd4ca] bg-white"><Play size={12} fill="currentColor" /></span> See how it works</button></div><div className="mt-12 flex items-center gap-5 text-xs text-[#78837d]"><span className="flex -space-x-2"><span className="h-7 w-7 rounded-full border-2 border-[#f7f8f3] bg-[#dcae91]" /><span className="h-7 w-7 rounded-full border-2 border-[#f7f8f3] bg-[#8ca7a3]" /><span className="h-7 w-7 rounded-full border-2 border-[#f7f8f3] bg-[#dbc86c]" /></span><span><strong className="text-[#14211f]">2,000+</strong> thoughtful creators are in the room</span></div></div>
      <div className="relative mx-auto w-full max-w-[560px] lg:ml-auto"><div className="relative rounded-[28px] border border-[#e0e7dd] bg-white p-3 shadow-[0_30px_70px_rgba(49,69,59,.12)]"><div className="rounded-[20px] bg-[#f3f6ee] p-5"><div className="mb-5 flex items-center justify-between"><div><p className="text-[11px] font-medium uppercase tracking-[.18em] text-[#8b978f]">Thursday, May 16</p><h2 className="mt-1 text-lg font-semibold">Your content, in motion</h2></div><span className="rounded-full bg-[#dff281] px-3 py-1 text-[11px] font-semibold text-[#3f581e]">This week</span></div><div className="grid grid-cols-7 gap-1.5 text-center text-[10px] text-[#8b978f]">{["M","T","W","T","F","S","S"].map((day, i) => <span key={`${day}-${i}`} className="py-2">{day}</span>)}{Array.from({ length: 21 }, (_, i) => <span key={i} className={`flex aspect-square items-center justify-center rounded-lg ${[3, 8, 15].includes(i) ? "bg-[#14211f] text-white" : [10, 16].includes(i) ? "bg-[#dff281] font-semibold text-[#3f581e]" : "bg-white text-[#63706b]"}`}>{i + 1}</span>)}</div><div className="mt-5 grid gap-2"><div className="flex items-center gap-3 rounded-xl bg-white p-3"><div className="h-9 w-9 rounded-lg bg-[#d4b093]" /><div className="flex-1"><p className="text-xs font-semibold">A slower morning</p><p className="mt-0.5 text-[10px] text-[#8b978f]">Instagram · Today, 9:30 AM</p></div><span className="h-2 w-2 rounded-full bg-[#a7c63f]" /></div><div className="flex items-center gap-3 rounded-xl bg-white p-3"><div className="h-9 w-9 rounded-lg bg-[#a9c0b0]" /><div className="flex-1"><p className="text-xs font-semibold">Notes from the studio</p><p className="mt-0.5 text-[10px] text-[#8b978f]">Facebook · Tomorrow</p></div><span className="h-2 w-2 rounded-full bg-[#e0aa64]" /></div></div></div></div><div className="absolute -bottom-7 -left-9 rounded-2xl border border-[#e0e7dd] bg-white px-4 py-3 shadow-[0_14px_35px_rgba(49,69,59,.1)]"><div className="flex items-center gap-2 text-xs font-semibold"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-[#dff281] text-[#3f581e]"><Check size={14} /></span> All channels ready</div></div></div>
    </section>
    <section id="features" className="border-y border-[#e2e8df] bg-white/60"><div className="mx-auto grid max-w-7xl gap-8 px-6 py-16 sm:grid-cols-3 lg:px-10">{features.map((feature, i) => <div key={feature.title} className="border-l border-[#dce4d9] pl-5"><span className="text-xs font-semibold tracking-[.18em] text-[#8aa431]">0{i + 1}</span><h3 className="mt-5 text-xl font-semibold tracking-tight">{feature.title}</h3><p className="mt-3 max-w-xs text-sm leading-6 text-[#6b7771]">{feature.text}</p></div>)}</div></section>
    <section id="how-it-works" className="mx-auto max-w-7xl px-6 py-24 lg:px-10 lg:py-32"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#8aa431]">How it works</p><h2 className="mt-5 max-w-md text-4xl font-semibold leading-tight tracking-[-.04em] sm:text-5xl">Make space for better ideas.</h2></div><div className="grid gap-0">{steps.map(([number, title, text]) => <div key={number} className="grid grid-cols-[60px_1fr] gap-5 border-t border-[#dce4d9] py-7"><span className="text-sm font-semibold text-[#8aa431]">{number}</span><div><h3 className="text-xl font-semibold">{title}</h3><p className="mt-2 max-w-lg text-sm leading-6 text-[#6b7771]">{text}</p></div></div>)}</div></div></section>
    <section id="pricing" className="bg-[#14211f] px-6 py-20 text-white lg:px-10"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#d7f36a]">Coming soon</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em]">Simple pricing for serious work.</h2><p className="mt-3 max-w-md text-sm leading-6 text-[#a8b4aa]">Start free while OnePost grows with you. Paid plans will add more channels, collaborators, and room to create.</p></div><Link href="/auth/signup" className="rounded-full bg-[#d7f36a] px-5 py-3 text-sm font-semibold text-[#14211f]">Join the early list <ArrowRight className="ml-2 inline" size={15} /></Link></div></section>
    <section className="mx-auto max-w-3xl px-6 py-24 lg:px-10"><p className="text-center text-xs font-semibold uppercase tracking-[.2em] text-[#8aa431]">Questions, answered</p><h2 className="mt-4 text-center text-4xl font-semibold tracking-[-.04em]">A clear start.</h2><div className="mt-10 divide-y divide-[#dce4d9]">{["Can I use OnePost for multiple platforms?", "When will publishing integrations be available?", "Is my content private?", "Can I cancel whenever I want?"].map(question => <details key={question} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between text-sm font-semibold">{question}<ChevronDown className="transition group-open:rotate-180" size={18} /></summary><p className="mt-3 max-w-xl text-sm leading-6 text-[#6b7771]">OnePost is designed to keep your content and account data scoped to you. Platform publishing is built around official OAuth integrations and will only activate once configured and tested.</p></details>)}</div></section>
    <footer className="border-t border-[#dce4d9] px-6 py-8 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 text-xs text-[#78837d] sm:flex-row"><span className="font-semibold text-[#14211f]">OnePost</span><span>© 2026 OnePost. Create once. Publish everywhere.</span><span className="flex gap-4"><Link href="/auth/login">Log in</Link><Link href="/auth/signup">Get started</Link></span></div></footer>
  </main>;
}