"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, Sparkles } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

export default function LoginPage() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false); const router = useRouter();
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setMessage(""); const client = createClient(); if (!client) { setMessage("Add your Supabase environment variables to enable sign in."); setLoading(false); return; } const { error } = await client.auth.signInWithPassword({ email, password }); if (error) setMessage(error.message); else router.push("/dashboard"); setLoading(false); }
  return <main className="flex min-h-screen items-center justify-center bg-[#f7f8f3] px-6 py-12"><div className="w-full max-w-md"><Link href="/" className="mb-12 flex items-center gap-2 text-sm text-[#63706b]"><ArrowLeft size={15} /> Back to OnePost</Link><div className="mb-8 flex items-center gap-2 font-semibold"><span className="flex h-8 w-8 items-center justify-center rounded-[10px] bg-[#14211f] text-[#d7f36a]"><Sparkles size={16} /></span>OnePost</div><h1 className="text-4xl font-semibold tracking-[-.04em]">Welcome back.</h1><p className="mt-3 text-sm text-[#63706b]">Pick up where your best work left off.</p><form onSubmit={submit} className="mt-9 space-y-5"><label className="block text-sm font-medium">Email<input required type="email" value={email} onChange={e => setEmail(e.target.value)} className="mt-2 w-full rounded-xl border border-[#d5ded3] bg-white px-4 py-3 outline-none focus:border-[#8aa431]" /></label><label className="block text-sm font-medium">Password<input required type="password" value={password} onChange={e => setPassword(e.target.value)} className="mt-2 w-full rounded-xl border border-[#d5ded3] bg-white px-4 py-3 outline-none focus:border-[#8aa431]" /></label><div className="flex justify-end"><Link href="/auth/forgot-password" className="text-xs font-medium text-[#6f8e28]">Forgot password?</Link></div>{message && <p role="alert" className="rounded-xl bg-[#fff1df] px-4 py-3 text-sm text-[#8a5b24]">{message}</p>}<button disabled={loading} className="w-full rounded-full bg-[#14211f] py-3.5 text-sm font-medium text-white disabled:opacity-50">{loading ? "Signing in..." : <>Sign in <ArrowRight className="ml-1 inline" size={15} /></>}</button></form><p className="mt-8 text-center text-sm text-[#63706b]">New to OnePost? <Link href="/auth/signup" className="font-semibold text-[#14211f]">Create an account</Link></p></div></main>;
}